# Generated by Django 5.2.5 on 2025-08-30 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200, unique=True)),
                ('number_of_departments', models.PositiveIntegerField(default=0, help_text='Automatically calculated number of departments', validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_employees', models.PositiveIntegerField(default=0, help_text='Automatically calculated number of employees', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
